[[redirects]]
  from = "https://grandmashive.com/*"
  to = "https://www.grandmashive.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/fewcon.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
